# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cff1dde4fcade75c079a6409ac9a89fd03ad3a0274ca30c30a665ac74980d37f2b1226cfaa0c4c7cee84e92750406a454debe10c44798f3926a79dd7296d64bf

test:
  secret_key_base: 656580eb69e90c62342e19c08366e58b7a68129c090e1080ca4390efb746834e19317e2b489a2f7eeff0c1cb0d78e3a250823e4bda9197dfccdf84dcef4be1f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
